# This workflow will do a clean installation of node dependencies, cache/restore them, build the 
# source code and run tests across different versions of node
# For more information see: 
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Yarn
      run: npm install -g yarn
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: cp dist/index.html dist/404.html  # GitHub Pages fallback
    
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@3.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # A verified email.
        email: ${{ secrets.EMAIL }}
        # Where static files are.
        build_dir: dist
        branch: gh-pages
        cname: ntpu-tool-test.littlechin.tw
